// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleMVC.Data.DataBase;

namespace PeopleMVC.Migrations
{
    [DbContext(typeof(PeopleContext))]
    partial class PeopleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeopleMVC.Models.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialSecurityNr")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasAlternateKey("SocialSecurityNr");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Berlin",
                            FirstName = "Tina",
                            LastName = "Zwanzig",
                            PhoneNr = "031-5092-333",
                            SocialSecurityNr = "9206901234"
                        },
                        new
                        {
                            Id = 2,
                            City = "Stockholm",
                            FirstName = "Olle",
                            LastName = "Larsson",
                            PhoneNr = "074-3232-356",
                            SocialSecurityNr = "9206902222"
                        },
                        new
                        {
                            Id = 3,
                            City = "Stockholm",
                            FirstName = "Karin",
                            LastName = "Andersson",
                            PhoneNr = "074-3244-444",
                            SocialSecurityNr = "9206901111"
                        },
                        new
                        {
                            Id = 4,
                            City = "Göteborg",
                            FirstName = "Fatima",
                            LastName = "Koh",
                            PhoneNr = "071-1234-123",
                            SocialSecurityNr = "9206905678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
